apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ce2-sli
  namespace: f5-ce
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "ce2-sli",
      "type": "ovn-k8s-cni-overlay",
      "topology": "layer2",
      "netAttachDefName": "f5-ce/ce2-sli",
      "mtu": 1400,
      "ipam": {}
    }
